### PR TITLE
Applied all of Shobana's suggestions.

### PR DESCRIPTION
**Pull request by marianalevineu**

### CODE REVIEW

**Comment by marianalevineu** [comment]
@ShobanaSekar  Thanks again for your review. I think I've addressed most of your review points, if you approve feel free to merge too. Thanks!

**Comment by dhml** [comment]
@marianalevineu, @ShobanaSekar, great!  Once @ShobanaSekar approves, @marianalevineu can merge.  We discussed that the pull request author/assignee should merge once fully approved so we should try and adhere to this pattern.  Thanks...

**Comment by marianalevineu** [comment]
Sure no problem @dhml  thanks!

**Review by dhml — APPROVED** [review]
@marianalevineu, @ShobanaSekar, I'm going to merge this so we can move forward with repository refactoring.  If these changes need further scrutiny, wait until after this repository has been incorporated into `northeastern-rc/hpc-scripts` and open a new branch/PR as appropriate.  Thanks...

**Pull request merged**
